sudo: false
language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
script: npm test
branches:
  only:
    - master
    - /^v[0-9]/
deploy:
  provider: npm
  email: 'public@erikdesjardins.io'
  api_key:
    secure: C5dKM/gMoY+L5OiOxARtpSqkJiPpBGz9XF5ZOx2PkZTQ2dMRZ+Y7RlC4TUVuxzAoaXVtDu+cxClrc0iWuNjr03I62EZ0RTM2ALcUaPjsiiMQ03x6K8DXI23x0KKw4t/Kcn+04aI1B4Ipmamzz346uinaa16q1hzxF3pc4TO4BDxMBheFA8LopCzLMBtVaL5aTk7eydYW/Eizb8L30wknBdOFjCLRmUSUERnkywYxj/y/7efCrdHFruaOhqtMARdG9AjlAw2p8FTDvtXdCpZKCATppBZrtpWC+tXWAaG8DbTHDYgx2shrYeomp3wuuxnLmxluWejuB8JufwupvNbOyaxyS5SO8waouz/lJ6WF6+izEGxTXLG8nWxunJLH/zjSfp0yuFRK2nClmpG/LcXTHMWtG3/xu3jMnstV1LGjjDWKiz37LKDYndJ/Xe1LFTpfGLKcJzC/fYb45Qk+A3+dCb5D8y/YBEWp2pZ14PZNGKkOm8JKo4cENYyrqi3WadgrAf3mxL0/Ch3j8FX3lBe32QxACLXmFtsEwhWKJVr4eqrMMFXl/MfVfR+LukuzIA4pMFv7GVgOL2MdGuIzEcL4jSskCm46xD1mplyikYL20H0zHXYaCeEZ9sCZPerIA6CX47ox4tXOKV/o1e8O8nSjVLcyfU4V3F5hSF/so2iZtzw=
  on:
    tags: true
    node: 5
